package teamp;
// Generated Jul 18, 2019 9:38:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bookingreport generated by hbm2java
 */
@Entity
@Table(name="bookingreport"
    ,catalog="blackriders"
)
public class Bookingreport  implements java.io.Serializable {


     private Integer id;
     private String bookingDate;
     private String resourceName;
     private String eventName;
     private String customerName;
     private String amount;

    public Bookingreport() {
    }

    public Bookingreport(String bookingDate, String resourceName, String eventName, String customerName, String amount) {
       this.bookingDate = bookingDate;
       this.resourceName = resourceName;
       this.eventName = eventName;
       this.customerName = customerName;
       this.amount = amount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="BookingDate", nullable=false, length=500)
    public String getBookingDate() {
        return this.bookingDate;
    }
    
    public void setBookingDate(String bookingDate) {
        this.bookingDate = bookingDate;
    }

    
    @Column(name="ResourceName", nullable=false, length=500)
    public String getResourceName() {
        return this.resourceName;
    }
    
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    
    @Column(name="EventName", nullable=false, length=500)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    
    @Column(name="CustomerName", nullable=false, length=500)
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    
    @Column(name="Amount", nullable=false, length=500)
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


